/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB9_NEW;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GUIInterfaceTransportasii extends javax.swing.JFrame {
Mobil mobil;
Motor motor;
    /**
     * Creates new form GUIInterfaceTransportasii
     */
    public GUIInterfaceTransportasii() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlat = new javax.swing.JTextField();
        txtHargaPerKm = new javax.swing.JTextField();
        chkLayanan = new javax.swing.JCheckBox();
        txtPilihMobil = new javax.swing.JButton();
        txtPilihMotor = new javax.swing.JButton();
        txtTampilkan = new javax.swing.JButton();
        txtReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nomor Plat:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Harga Per Km:");

        chkLayanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkLayanan.setText("Dengan Supir/ Helm");

        txtPilihMobil.setText("Pilih Mobil");
        txtPilihMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilihMobilActionPerformed(evt);
            }
        });

        txtPilihMotor.setText("Pilih Motor");
        txtPilihMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilihMotorActionPerformed(evt);
            }
        });

        txtTampilkan.setText("Tampilkan Info");
        txtTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTampilkanActionPerformed(evt);
            }
        });

        txtReset.setText("Reset");
        txtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResetActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlat)
                                    .addComponent(txtHargaPerKm, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPilihMotor, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(txtPilihMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkLayanan)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReset)
                                    .addComponent(txtTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPilihMobil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHargaPerKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPilihMotor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLayanan)
                    .addComponent(txtTampilkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtReset)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPilihMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilihMobilActionPerformed
        // TODO add your handling code here:
        
        String plat = txtPlat.getText();
        double harga = Double.parseDouble(txtHargaPerKm.getText());
        boolean layanan = chkLayanan.isSelected();

        mobil = new Mobil(plat, harga, layanan);
        JOptionPane.showMessageDialog(null, "Mobil dipilih!");
    }//GEN-LAST:event_txtPilihMobilActionPerformed

    private void txtPilihMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilihMotorActionPerformed
        // TODO add your handling code here:
        String plat = txtPlat.getText();
        double harga = Double.parseDouble(txtHargaPerKm.getText());
        boolean layanan = chkLayanan.isSelected();

        motor = new Motor(plat, harga, layanan);
        JOptionPane.showMessageDialog(null, "Motor dipilih!");
    }//GEN-LAST:event_txtPilihMotorActionPerformed

    private void txtTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTampilkanActionPerformed
        // TODO add your handling code here:
        if (mobil != null) {
            txtArea.setText("== Informasi Mobil ==\n");
            txtArea.append("Plat: " + mobil.getNomorPlat() + "\n");
            txtArea.append("Harga per Km: " + mobil.getHargaPerKm() + "\n");
            txtArea.append("Layanan: " + (mobil.isSupir() ? "Dengan Supir" : "Tanpa Supir") + "\n");
        } else if (motor != null) {
            txtArea.setText("== Informasi Motor ==\n");
            txtArea.append("Plat: " + motor.getNomorPlat() + "\n");
            txtArea.append("Harga per Km: " + motor.getHargaPerKm() + "\n");
            txtArea.append("Layanan: " + (motor.isHelm() ? "Dengan Helm" : "Tanpa Helm") + "\n");
        } else {
            txtArea.setText("Belum ada transportasi yang dipilih.");
        }
    }//GEN-LAST:event_txtTampilkanActionPerformed

    private void txtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResetActionPerformed
        // TODO add your handling code here:
        txtPlat.setText("");
        txtHargaPerKm.setText("");
        chkLayanan.setSelected(false);
        txtArea.setText("");
        mobil = null;
        motor = null;
    }//GEN-LAST:event_txtResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInterfaceTransportasii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInterfaceTransportasii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInterfaceTransportasii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInterfaceTransportasii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInterfaceTransportasii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtHargaPerKm;
    private javax.swing.JButton txtPilihMobil;
    private javax.swing.JButton txtPilihMotor;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JButton txtReset;
    private javax.swing.JButton txtTampilkan;
    // End of variables declaration//GEN-END:variables
}
